# Generated by Django 3.2.18 on 2023-09-21 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='menupermissions',
            options={'permissions': [('config_document_type', 'Configurar Tipo Documento'), ('config_bank_type_subtype_account', 'Configurar Banco Tipos y Subtipo Cuenta'), ('menu_view_referred', 'Menu ver referidos')]},
        ),
    ]
