# Generated by Django 3.2.18 on 2023-09-21 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_alter_menupermissions_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='menupermissions',
            options={'permissions': [('menu_config_document_type', 'Configurar Tipo Documento'), ('menu_config_bank_type_subtype_account', 'Configurar Banco Tipos y Subtipo Cuenta'), ('menu_view_referred_list', 'Menu ver referidos')]},
        ),
    ]
