# Generated by Django 3.2.18 on 2023-09-08 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccountSubtype',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.BooleanField(default=True)),
                ('value', models.CharField(max_length=128)),
                ('name', models.CharField(max_length=128)),
                ('description', models.CharField(max_length=128)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AccountType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.BooleanField(default=True)),
                ('value', models.CharField(max_length=128)),
                ('name', models.CharField(max_length=128)),
                ('description', models.CharField(max_length=128)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.BooleanField(default=True)),
                ('institution_name', models.CharField(max_length=128)),
                ('uuid', models.CharField(max_length=128)),
                ('country', models.CharField(max_length=16)),
                ('network', models.CharField(max_length=16)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ConnectAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.BooleanField(default=True)),
                ('institution_uuid', models.CharField(max_length=128)),
                ('account_number', models.CharField(max_length=128)),
                ('routing_number', models.CharField(max_length=128)),
                ('type', models.CharField(max_length=128)),
                ('subtype', models.CharField(max_length=128)),
                ('user_authorization', models.BooleanField(default=True)),
                ('existing_end_user_id', models.CharField(blank=True, max_length=128, null=True)),
                ('uuid', models.CharField(blank=True, max_length=128, null=True)),
                ('code', models.CharField(blank=True, max_length=128, null=True)),
                ('source_connect_link', models.CharField(blank=True, max_length=128, null=True)),
                ('current_status', models.CharField(blank=True, max_length=64, null=True)),
                ('remarks', models.CharField(blank=True, max_length=64, null=True)),
                ('institution', models.CharField(blank=True, max_length=128, null=True)),
                ('name', models.CharField(blank=True, max_length=128, null=True)),
                ('official_name', models.CharField(blank=True, max_length=128, null=True)),
                ('last_4', models.CharField(blank=True, max_length=62, null=True)),
                ('capabilities', models.CharField(blank=True, max_length=128, null=True)),
                ('end_user', models.JSONField(blank=True, null=True)),
                ('primary_reference', models.CharField(blank=True, max_length=128, null=True)),
                ('secondary_reference', models.CharField(blank=True, max_length=128, null=True)),
                ('metadata', models.JSONField(blank=True, null=True)),
                ('date_created_gmt', models.DateTimeField(blank=True, null=True)),
                ('date_updated_gmt', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Token',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.BooleanField(default=True)),
                ('token_type', models.CharField(max_length=126)),
                ('expires_in', models.IntegerField()),
                ('access_token', models.TextField()),
            ],
            options={
                'ordering': ['-created_at'],
                'get_latest_by': 'created_at',
            },
        ),
        migrations.CreateModel(
            name='UserDruo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.BooleanField(default=True)),
                ('uuid', models.CharField(blank=True, max_length=128, null=True)),
                ('code', models.CharField(blank=True, max_length=128, null=True)),
                ('current_status', models.CharField(blank=True, max_length=128, null=True)),
                ('metadata', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
