# Generated by Django 3.2.18 on 2023-09-18 22:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('druo', '0002_userdruo_user_devise'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bank',
            options={'ordering': ['institution_name']},
        ),
    ]
