# Generated by Django 3.2.18 on 2023-09-08 15:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cities_light', '0011_alter_city_country_alter_city_region_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Workplace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.BooleanField(default=True)),
                ('occupation', models.CharField(blank=True, choices=[('INDEPENDIENTE', 'Independiente'), ('EMPLEADO', 'Empleado'), ('OTRO', 'Otro')], max_length=126, null=True)),
                ('company_name', models.CharField(blank=True, max_length=128, null=True)),
                ('company_position', models.CharField(blank=True, max_length=128, null=True)),
                ('company_phone', models.CharField(blank=True, max_length=128, null=True)),
                ('company_address', models.CharField(blank=True, max_length=128, null=True)),
                ('company_zip', models.CharField(blank=True, max_length=64, null=True)),
                ('company_city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='workplace_city', to='cities_light.subregion')),
                ('company_country', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='workplace_country', to='cities_light.country')),
                ('company_region', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='workplace_region', to='cities_light.region')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
