# Generated by Django 3.2.18 on 2023-09-08 15:57

import apps.fiducia.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cities_light', '0011_alter_city_country_alter_city_region_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fiducia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=128)),
                ('phone', models.CharField(blank=True, max_length=128, null=True)),
                ('address', models.CharField(blank=True, max_length=128, null=True)),
                ('zip_code', models.CharField(blank=True, max_length=64, null=True)),
                ('nit', models.CharField(blank=True, max_length=64, null=True, unique=True)),
                ('camara_comercio', models.CharField(blank=True, max_length=64, null=True, unique=True)),
                ('logo', models.ImageField(upload_to=apps.fiducia.models.fiducia_file_path)),
                ('informacion', models.TextField(blank=True, null=True)),
                ('area', models.CharField(blank=True, max_length=128, null=True)),
                ('city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='cities_light.subregion')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cities_light.country')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
