# Generated by Django 3.2.18 on 2023-09-08 15:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('info_financial', '0001_initial'),
        ('cities_light', '0011_alter_city_country_alter_city_region_and_more'),
        ('fiducia', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fiducia',
            name='financial_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cuenta_fiducia', to='info_financial.financial'),
        ),
        migrations.AddField(
            model_name='fiducia',
            name='region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='cities_light.region'),
        ),
    ]
