# Generated by Django 3.2.18 on 2023-09-20 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='kyc_validated',
            field=models.CharField(choices=[('pending_document', 'Pendiente por cargar documento'), ('ready_for_kyc', 'Pendiente por subir a WeeTrust'), ('validating_document', 'Documento en Validación'), ('fail_document', 'Fallo en Documento'), ('sucessfull_document', 'KYC Validado')], default='pending_document', max_length=64),
        ),
    ]
