# Generated by Django 3.2.18 on 2023-11-03 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_alter_user_last_password_change'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='last_password_change',
            field=models.DateField(blank=True, null=True),
        ),
    ]
