# Generated by Django 3.2.18 on 2023-11-16 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_rename_failed_atemps_user_failed_attempts'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='last_failed_access',
            field=models.DateField(blank=True, null=True),
        ),
    ]
