# Generated by Django 3.2.18 on 2023-11-16 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_user_last_failed_access'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='last_failed_access',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
