# Generated by Django 3.2.18 on 2023-11-16 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0011_alter_user_last_failed_access'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='last_frontend_access',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
