# Generated by Django 3.2.18 on 2023-11-17 15:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0012_user_last_frontend_access'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='last_frontend_access',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
