# Generated by Django 3.2.18 on 2023-09-08 15:57

import apps.asset.models
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ActivoCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=126, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ActivoInversion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.BooleanField(default=True)),
                ('codigo', models.CharField(max_length=126, unique=True)),
                ('nombre', models.CharField(max_length=126)),
                ('descripcion_proyecto', models.TextField(blank=True, null=True)),
                ('dimension_m2', models.DecimalField(decimal_places=2, max_digits=12)),
                ('direccion', models.CharField(max_length=126)),
                ('latitud', models.FloatField(blank=True, null=True)),
                ('longitud', models.FloatField(blank=True, null=True)),
                ('descripcion_ubicacion', models.TextField(blank=True, null=True)),
                ('area_construida_m2', models.DecimalField(decimal_places=2, max_digits=12)),
                ('area_gla_m2', models.DecimalField(decimal_places=2, max_digits=12)),
                ('area_vendible_m2', models.DecimalField(decimal_places=2, max_digits=12)),
                ('area_lote_m2', models.DecimalField(decimal_places=2, max_digits=12)),
                ('ano_construccion', models.IntegerField()),
                ('matricula_inmobiliaria', models.CharField(blank=True, max_length=126, null=True)),
                ('cedula_catastral', models.CharField(blank=True, max_length=126, null=True)),
                ('certificado_tradicion_libertad', models.FileField(blank=True, null=True, upload_to=apps.asset.models.asset_file_path, validators=[django.core.validators.FileExtensionValidator(['pdf'])])),
                ('canon_arriendo', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('contrato_arriendo', models.FileField(blank=True, null=True, upload_to=apps.asset.models.asset_file_path, validators=[django.core.validators.FileExtensionValidator(['pdf'])])),
                ('nombre_arrendatario', models.CharField(blank=True, max_length=126, null=True)),
                ('informacion_arrendatario', models.TextField(blank=True, null=True)),
                ('vencimiento_contrato_arrendamiento', models.DateField(blank=True, null=True)),
                ('imagen_1', models.ImageField(blank=True, null=True, upload_to=apps.asset.models.asset_file_path)),
                ('imagen_2', models.ImageField(blank=True, null=True, upload_to=apps.asset.models.asset_file_path)),
                ('imagen_3', models.ImageField(blank=True, null=True, upload_to=apps.asset.models.asset_file_path)),
                ('imagen_4', models.ImageField(blank=True, null=True, upload_to=apps.asset.models.asset_file_path)),
                ('imagen_5', models.ImageField(blank=True, null=True, upload_to=apps.asset.models.asset_file_path)),
                ('valor_activo', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('nuevo_certificado_tradicion_libertad', models.FileField(blank=True, null=True, upload_to=apps.asset.models.asset_file_path, validators=[django.core.validators.FileExtensionValidator(['pdf'])])),
                ('nuevo_escritura', models.FileField(blank=True, null=True, upload_to=apps.asset.models.asset_file_path, validators=[django.core.validators.FileExtensionValidator(['pdf'])])),
                ('fideicomiso_revisado', models.BooleanField(blank=True, null=True)),
                ('estado_aprobacion', models.CharField(blank=True, choices=[('Activo sin validar', 'Activo sin validar'), ('Pendiente respuesta del Propietario', 'Pendiente respuesta del Propietario'), ('Activo aprobado por el Sponsor', 'Activo aprobado por el Sponsor'), ('Pendiente respuesta del Sponsor', 'Pendiente respuesta del Sponsor'), ('Activo aprobado por Devise', 'Activo aprobado por Devise')], max_length=126, null=True)),
                ('valor_token', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('tokens_totales', models.IntegerField(blank=True, null=True)),
                ('tokens_disponibles', models.IntegerField(blank=True, null=True)),
                ('tir_ea', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('pago_rendimiento', models.CharField(blank=True, max_length=255, null=True)),
                ('tenencia_sugerida', models.CharField(blank=True, max_length=255, null=True)),
                ('renta_mensual', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('renta_por_m2', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('incremento_anual', models.CharField(blank=True, max_length=255, null=True)),
                ('modelo_financiero', models.FileField(blank=True, null=True, upload_to=apps.asset.models.asset_file_path, validators=[django.core.validators.FileExtensionValidator(['pdf', 'xls', 'xlsx'])])),
                ('clase_inversion', models.CharField(blank=True, max_length=255, null=True)),
                ('plazo_contrato', models.CharField(blank=True, max_length=255, null=True)),
                ('teaser', models.FileField(blank=True, null=True, upload_to=apps.asset.models.asset_file_path, validators=[django.core.validators.FileExtensionValidator(['pdf'])])),
                ('no_id_fideicomiso', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('nombre_fideicomiso', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('inmueble_publicado', models.BooleanField(blank=True, null=True)),
                ('documento_cesion', models.FileField(blank=True, null=True, upload_to=apps.asset.models.asset_file_path)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AprobacionMinuta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.BooleanField(default=True)),
                ('minuta', models.FileField(blank=True, null=True, upload_to=apps.asset.models.asset_file_path)),
                ('aprobado_fiducia', models.BooleanField(blank=True, null=True)),
                ('aprobado_notario', models.BooleanField(blank=True, null=True)),
                ('aprobado_sponsor', models.BooleanField(blank=True, null=True)),
                ('aprobado_propietario', models.BooleanField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.BooleanField(default=True)),
                ('nombre', models.CharField(max_length=126)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='asset/categoria/')),
                ('color', models.CharField(max_length=16)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ConstitucionFideicomiso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.BooleanField(default=True)),
                ('constitucion_fideicomiso', models.FileField(blank=True, null=True, upload_to=apps.asset.models.asset_file_path, validators=[django.core.validators.FileExtensionValidator(['pdf'])])),
                ('aprobado_fiducia', models.BooleanField(blank=True, null=True)),
                ('aprobado_devise', models.BooleanField(blank=True, null=True)),
                ('aprobado_sponsor', models.BooleanField(blank=True, null=True)),
                ('aprobado_propietario', models.BooleanField(blank=True, null=True)),
                ('id_weetrust_document', models.CharField(max_length=126)),
                ('fideicomiso_firmado', models.FileField(blank=True, null=True, upload_to=apps.asset.models.asset_file_path, validators=[django.core.validators.FileExtensionValidator(['pdf'])])),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FeedbackActivoInversion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.BooleanField(default=True)),
                ('mensaje', models.TextField(blank=True, null=True)),
                ('archivo_adjunto', models.FileField(blank=True, null=True, upload_to=apps.asset.models.asset_file_path_feedback)),
                ('estado_actual', models.CharField(max_length=126)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FeedbackAprobacionMinuta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.BooleanField(default=True)),
                ('mensaje', models.TextField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TipoProyecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.BooleanField(default=True)),
                ('nombre', models.CharField(max_length=126)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='asset/tipoproyecto/')),
                ('color', models.CharField(max_length=16)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FeedbackKPI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.BooleanField(default=True)),
                ('mensaje', models.TextField(blank=True, null=True)),
                ('activo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='asset.activoinversion')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
