# Generated by Django 3.2.18 on 2023-09-08 15:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cities_light', '0011_alter_city_country_alter_city_region_and_more'),
        ('asset', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sponsor_company', '0002_sponsorcompany_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedbackkpi',
            name='destinatario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='FeedbackKPI_destinatario', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='feedbackkpi',
            name='remitente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='FeedbackKPI_remitente', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='feedbackaprobacionminuta',
            name='activo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='asset.activoinversion'),
        ),
        migrations.AddField(
            model_name='feedbackaprobacionminuta',
            name='destinatario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='FeedbackAprobacionMinuta_destinatario', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='feedbackaprobacionminuta',
            name='remitente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='FeedbackAprobacionMinuta_remitente', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='feedbackactivoinversion',
            name='activo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='asset.activoinversion'),
        ),
        migrations.AddField(
            model_name='feedbackactivoinversion',
            name='destinatario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='FeedbackActivoInversion_destinatario', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='feedbackactivoinversion',
            name='remitente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='FeedbackActivoInversion_remitente', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='constitucionfideicomiso',
            name='activo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='asset.activoinversion'),
        ),
        migrations.AddField(
            model_name='aprobacionminuta',
            name='activo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='asset.activoinversion'),
        ),
        migrations.AddField(
            model_name='activoinversion',
            name='categoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='asset.categoria'),
        ),
        migrations.AddField(
            model_name='activoinversion',
            name='ciudad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='cities_light.subregion'),
        ),
        migrations.AddField(
            model_name='activoinversion',
            name='gerente_negocio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='gerente_negocio', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='activoinversion',
            name='pais',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='cities_light.country'),
        ),
        migrations.AddField(
            model_name='activoinversion',
            name='propietario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='propietario', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='activoinversion',
            name='region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='cities_light.region'),
        ),
        migrations.AddField(
            model_name='activoinversion',
            name='sponsor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='sponsor_company.sponsorcompany'),
        ),
        migrations.AddField(
            model_name='activoinversion',
            name='tipo_proyecto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='asset.tipoproyecto'),
        ),
    ]
