# Generated by Django 3.2.18 on 2023-09-22 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0004_auto_20230922_0927'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activoinversion',
            options={'permissions': [('approved_activo_fiducia', 'Puede aprovar activo para la Fiducia')]},
        ),
    ]
