# Generated by Django 3.2.18 on 2023-09-22 20:23

import apps.asset.models
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0006_auto_20230922_1455'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fideicomiso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.BooleanField(default=True)),
                ('constitucion_fideicomiso', models.FileField(blank=True, null=True, upload_to=apps.asset.models.asset_file_path, validators=[django.core.validators.FileExtensionValidator(['pdf'])])),
                ('email_fiducia', models.EmailField(blank=True, max_length=128, null=True)),
                ('name_fiducia', models.CharField(blank=True, max_length=128, null=True)),
                ('aprobado_fiducia', models.BooleanField(blank=True, null=True)),
                ('email_devise', models.EmailField(blank=True, max_length=128, null=True)),
                ('name_devise', models.CharField(blank=True, max_length=128, null=True)),
                ('aprobado_devise', models.BooleanField(blank=True, null=True)),
                ('email_sponsor', models.EmailField(blank=True, max_length=128, null=True)),
                ('name_sponsor', models.CharField(blank=True, max_length=128, null=True)),
                ('aprobado_sponsor', models.BooleanField(blank=True, null=True)),
                ('email_propietario', models.EmailField(blank=True, max_length=128, null=True)),
                ('name_propietario', models.CharField(blank=True, max_length=128, null=True)),
                ('aprobado_propietario', models.BooleanField(blank=True, null=True)),
                ('correo_enviado', models.BooleanField(default=False)),
                ('id_weetrust_document', models.CharField(blank=True, max_length=126, null=True)),
                ('fideicomiso_firmado', models.FileField(blank=True, null=True, upload_to=apps.asset.models.asset_file_path, validators=[django.core.validators.FileExtensionValidator(['pdf'])])),
                ('activo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='asset.activoinversion')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='ConstitucionFideicomiso',
        ),
    ]
