# Generated by Django 3.2.18 on 2023-09-22 20:38

import apps.asset.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0007_auto_20230922_1523'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fideicomiso',
            name='constitucion_fideicomiso',
        ),
        migrations.AddField(
            model_name='fideicomiso',
            name='fideicomiso',
            field=models.FileField(blank=True, null=True, upload_to=apps.asset.models.asset_file_path, validators=[django.core.validators.FileExtensionValidator(['pdf'])]),
        ),
    ]
