# Generated by Django 3.2.18 on 2023-09-22 20:41

import apps.asset.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0008_auto_20230922_1538'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fideicomiso',
            name='fideicomiso',
            field=models.FileField(blank=True, null=True, upload_to=apps.asset.models.asset_file_path),
        ),
    ]
