# Generated by Django 3.2.18 on 2023-09-22 21:15

import apps.asset.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0009_alter_fideicomiso_fideicomiso'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fideicomiso',
            name='fideicomiso',
            field=models.FileField(upload_to=apps.asset.models.asset_file_path, validators=[django.core.validators.FileExtensionValidator(['pdf'])]),
        ),
    ]
