# Generated by Django 3.2.18 on 2023-09-25 16:28

import apps.asset.models
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('asset', '0010_alter_fideicomiso_fideicomiso'),
    ]

    operations = [
        migrations.AddField(
            model_name='fideicomiso',
            name='gerente_negocio',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='user.user'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='activoinversion',
            name='estado_aprobacion',
            field=models.CharField(blank=True, choices=[('Activo pendiente aprobacion Sponsor', 'Activo pendiente aprobacion Sponsor '), ('Pendiente respuesta del Propietario', 'Pendiente respuesta del Propietario'), ('Activo aprobado por el Sponsor', 'Activo aprobado por el Sponsor'), ('Pendiente respuesta del Sponsor', 'Pendiente respuesta del Sponsor'), ('Activo aprobado por Devise', 'Activo aprobado por Devise'), ('Activo aprobado por Fiducia', 'Activo aprobado por la Fiducia'), ('Activo con fideicomiso cargado', 'Activo con fideicomiso pendiente por enviar')], max_length=126, null=True),
        ),
        migrations.AlterField(
            model_name='fideicomiso',
            name='fideicomiso',
            field=models.FileField(upload_to=apps.asset.models.asset_fideicomiso_file_path, validators=[django.core.validators.FileExtensionValidator(['pdf'])]),
        ),
        migrations.AlterField(
            model_name='fideicomiso',
            name='fideicomiso_firmado',
            field=models.FileField(blank=True, null=True, upload_to=apps.asset.models.asset_fideicomiso_file_path, validators=[django.core.validators.FileExtensionValidator(['pdf'])]),
        ),
    ]
