# Generated by Django 3.2.18 on 2023-09-26 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0013_alter_activoinversion_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='EstadoAprobacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.BooleanField(default=True)),
                ('nombre', models.CharField(max_length=125)),
                ('paso', models.DecimalField(decimal_places=1, max_digits=3)),
                ('codigo', models.CharField(max_length=125)),
                ('color', models.CharField(max_length=125)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='activoinversion',
            name='estado_aprobacion',
        ),
    ]
