# Generated by Django 3.2.18 on 2023-09-26 17:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0014_auto_20230926_1214'),
    ]

    operations = [
        migrations.AddField(
            model_name='activoinversion',
            name='estado_aprobacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='asset.estadoaprobacion'),
        ),
    ]
