# Generated by Django 3.2.18 on 2023-09-27 19:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0016_alter_estadoaprobacion_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fideicomiso',
            old_name='correo_enviado',
            new_name='enviado_weetrust',
        ),
    ]
