# Generated by Django 3.2.18 on 2023-09-28 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0017_rename_correo_enviado_fideicomiso_enviado_weetrust'),
    ]

    operations = [
        migrations.AddField(
            model_name='fideicomiso',
            name='response_weetrust',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
