# Generated by Django 3.2.18 on 2023-10-03 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0019_fideicomiso_firmado_todos'),
    ]

    operations = [
        migrations.AddField(
            model_name='fideicomiso',
            name='devise_json',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fideicomiso',
            name='devise_sesion',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='fideicomiso',
            name='fiducia_json',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fideicomiso',
            name='fiducia_sesion',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='fideicomiso',
            name='propietario_json',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fideicomiso',
            name='propietario_sesion',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='fideicomiso',
            name='sponsor_json',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fideicomiso',
            name='sponsor_sesion',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
