# Generated by Django 3.2.18 on 2023-10-04 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0020_auto_20231003_1804'),
    ]

    operations = [
        migrations.AddField(
            model_name='fideicomiso',
            name='devise_biometric_url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='fideicomiso',
            name='fiducia_biometric_url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='fideicomiso',
            name='propietario_biometric_url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='fideicomiso',
            name='sponsor_biometric_url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
