# Generated by Django 3.2.18 on 2023-10-12 16:55

import apps.asset.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('asset', '0023_auto_20231003_2121'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedbackMinutaEscrituracion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.BooleanField(default=True)),
                ('mensaje', models.TextField(blank=True, null=True)),
                ('destinatario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='FeedbackMinuta_destinatario', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MinutaEscrituracion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.BooleanField(default=True)),
                ('archivo', models.FileField(blank=True, null=True, upload_to=apps.asset.models.asset_file_path)),
                ('aprobado_fiducia', models.BooleanField(blank=True, null=True)),
                ('aprobado_notario', models.BooleanField(blank=True, null=True)),
                ('aprobado_sponsor', models.BooleanField(blank=True, null=True)),
                ('aprobado_propietario', models.BooleanField(blank=True, null=True)),
                ('activo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='asset.activoinversion')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='feedbackaprobacionminuta',
            name='activo',
        ),
        migrations.RemoveField(
            model_name='feedbackaprobacionminuta',
            name='destinatario',
        ),
        migrations.RemoveField(
            model_name='feedbackaprobacionminuta',
            name='remitente',
        ),
        migrations.AlterModelOptions(
            name='feedbackactivoinversion',
            options={'ordering': ['-created_at']},
        ),
        migrations.DeleteModel(
            name='AprobacionMinuta',
        ),
        migrations.DeleteModel(
            name='FeedbackAprobacionMinuta',
        ),
        migrations.AddField(
            model_name='feedbackminutaescrituracion',
            name='minuta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='asset.minutaescrituracion'),
        ),
        migrations.AddField(
            model_name='feedbackminutaescrituracion',
            name='remitente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='FeedbackMinuta_remitente', to=settings.AUTH_USER_MODEL),
        ),
    ]
