# Generated by Django 3.2.18 on 2023-10-13 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0024_auto_20231012_1155'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='fideicomiso',
            unique_together={('activo',)},
        ),
    ]
