# Generated by Django 3.2.18 on 2023-10-17 15:33

import apps.asset.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('notaria', '0001_initial'),
        ('asset', '0025_alter_fideicomiso_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='activoinversion',
            name='notaria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='notaria.notaria'),
        ),
        migrations.AlterField(
            model_name='minutaescrituracion',
            name='archivo',
            field=models.FileField(blank=True, null=True, upload_to=apps.asset.models.asset_minuta_path),
        ),
        migrations.AlterUniqueTogether(
            name='minutaescrituracion',
            unique_together={('activo',)},
        ),
    ]
