# Generated by Django 3.2.18 on 2023-10-17 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0026_auto_20231017_1033'),
    ]

    operations = [
        migrations.AddField(
            model_name='minutaescrituracion',
            name='minuta_aprobada',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
