# Generated by Django 3.2.18 on 2023-10-17 22:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0027_minutaescrituracion_minuta_aprobada'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedbackminutaescrituracion',
            name='minuta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='asset.minutaescrituracion'),
        ),
    ]
