# Generated by Django 3.2.18 on 2023-10-18 00:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0029_auto_20231017_1931'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedbackminutaescrituracion',
            name='mensaje',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='feedbackminutaescrituracion',
            name='minuta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='asset.minutaescrituracion'),
        ),
    ]
