# Generated by Django 3.2.18 on 2023-10-20 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0030_auto_20231017_1938'),
    ]

    operations = [
        migrations.RenameField(
            model_name='activoinversion',
            old_name='nuevo_escritura',
            new_name='nueva_escritura',
        ),
    ]
