# Generated by Django 3.2.18 on 2023-10-26 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0031_rename_nuevo_escritura_activoinversion_nueva_escritura'),
    ]

    operations = [
        migrations.AddField(
            model_name='activoinversion',
            name='id_contrato',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
