# Generated by Django 3.2.18 on 2023-11-09 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0033_activoinversion_metadata_smartcontract'),
    ]

    operations = [
        migrations.RenameField(
            model_name='activoinversion',
            old_name='id_contrato',
            new_name='id_smartcontract',
        ),
    ]
