# Generated by Django 3.2.18 on 2023-12-13 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0034_rename_id_contrato_activoinversion_id_smartcontract'),
    ]

    operations = [
        migrations.AddField(
            model_name='fideicomiso',
            name='devise_signing_url',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='fideicomiso',
            name='fiducia_signing_url',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='fideicomiso',
            name='propietario_signing_url',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='fideicomiso',
            name='sponsor_signing_url',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
    ]
