# Generated by Django 3.2.18 on 2024-04-22 21:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0035_auto_20231213_1021'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivoInversionSmartContract2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.BooleanField(default=True)),
                ('contractAddress', models.CharField(max_length=84, unique=True)),
                ('metadata_smartcontract', models.JSONField()),
                ('environment_id', models.CharField(max_length=255)),
                ('node_id', models.CharField(max_length=255)),
                ('zone_domain', models.CharField(max_length=255)),
                ('gateway_api', models.CharField(max_length=255)),
                ('kld_from', models.CharField(max_length=255)),
                ('kld_sync', models.BooleanField(blank=True, null=True)),
                ('activo_inversion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activo_inversion_id', to='asset.activoinversion')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
