# Generated by Django 3.2.18 on 2024-04-22 21:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0036_activoinversionsmartcontract2'),
    ]

    operations = [
        migrations.RenameField(
            model_name='activoinversionsmartcontract2',
            old_name='contractAddress',
            new_name='contract_address',
        ),
    ]
