# Generated by Django 3.2.18 on 2023-09-08 15:57

import apps.info_socioeconomic.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cities_light', '0011_alter_city_country_alter_city_region_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OriginFund',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=128)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Socioeconomic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.BooleanField(default=True)),
                ('monthly_income', models.DecimalField(decimal_places=3, max_digits=15)),
                ('other_income', models.BooleanField(default=False)),
                ('value_other_income', models.DecimalField(blank=True, decimal_places=3, max_digits=15, null=True)),
                ('monthly_expenses', models.DecimalField(decimal_places=3, max_digits=15)),
                ('total_assets', models.DecimalField(decimal_places=3, max_digits=15)),
                ('total_liabilities', models.DecimalField(decimal_places=3, max_digits=15)),
                ('income_explanation', models.TextField(blank=True, null=True)),
                ('manage_public_resources', models.BooleanField(default=False)),
                ('links_with_pep', models.BooleanField(default=False)),
                ('foreign_currency_operations', models.BooleanField(default=False)),
                ('foreign_operations_value', models.DecimalField(blank=True, decimal_places=3, max_digits=15, null=True)),
                ('outside_tax_obligation', models.BooleanField(default=False)),
                ('tin_number_or_equivalent', models.CharField(blank=True, max_length=128, null=True)),
                ('is_declarant', models.BooleanField(default=False)),
                ('last_year_income_statement', models.FileField(blank=True, null=True, upload_to=apps.info_socioeconomic.models.owner_file_path)),
                ('economic_dependency_letter', models.FileField(blank=True, null=True, upload_to=apps.info_socioeconomic.models.owner_file_path)),
                ('certified_public_accountant', models.FileField(blank=True, null=True, upload_to=apps.info_socioeconomic.models.owner_file_path)),
                ('profesional_accountant_card', models.FileField(blank=True, null=True, upload_to=apps.info_socioeconomic.models.owner_file_path)),
                ('pension_payment_receipt', models.FileField(blank=True, null=True, upload_to=apps.info_socioeconomic.models.owner_file_path)),
                ('source_funds_support', models.FileField(blank=True, null=True, upload_to=apps.info_socioeconomic.models.owner_file_path)),
                ('country_of_tax_residence', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='country_tax_residence', to='cities_light.country')),
                ('foreign_operations_country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='country_foreign_operations', to='cities_light.country')),
                ('origin_of_funds', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='info_socioeconomic.originfund')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
