# Generated by Django 3.2.18 on 2023-09-08 15:57

import apps.info_financial.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('druo', '0001_initial'),
        ('fiducia', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Financial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.BooleanField(default=True)),
                ('account_number', models.CharField(blank=True, max_length=128, null=True)),
                ('certification_file', models.FileField(upload_to=apps.info_financial.models.owner_file_path)),
                ('aba_code', models.CharField(blank=True, max_length=64, null=True)),
                ('swift_code', models.CharField(blank=True, max_length=64, null=True)),
                ('account_subtype', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='account_type', to='druo.accountsubtype')),
                ('account_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='account_type', to='druo.accounttype')),
                ('bank', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='banking_entity', to='druo.bank')),
                ('fiducia', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pertenece_a_fiducia', to='fiducia.fiducia')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
