# Generated by Django 3.2.18 on 2024-03-08 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kaleido', '0002_alter_wallet_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallet',
            name='environment_id',
            field=models.CharField(default='environment_id', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='wallet',
            name='wallet_service',
            field=models.CharField(default='u0gvt7k3aw', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='wallet',
            name='zone_domain',
            field=models.CharField(default='us0-aws', max_length=255),
            preserve_default=False,
        ),
    ]
