# Generated by Django 3.2.18 on 2024-03-08 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kaleido', '0003_auto_20240308_0915'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallet',
            name='consortia_id',
            field=models.CharField(default='u0b2d58owm', max_length=255),
            preserve_default=False,
        ),
    ]
