# Generated by Django 3.2.18 on 2024-03-08 20:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kaleido', '0004_wallet_consortia_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wallet',
            old_name='consortia_id',
            new_name='consortia',
        ),
    ]
