# Generated by Django 3.2.18 on 2024-04-22 21:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0036_activoinversionsmartcontract2'),
        ('kaleido', '0005_rename_consortia_id_wallet_consortia'),
    ]

    operations = [
        migrations.CreateModel(
            name='WalletSmartContract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.BooleanField(default=True)),
                ('id_wallet', models.CharField(max_length=50)),
                ('secret', models.CharField(max_length=255)),
                ('environment_id', models.CharField(max_length=255)),
                ('wallet_service', models.CharField(max_length=255)),
                ('zone_domain', models.CharField(max_length=255)),
                ('consortia', models.CharField(max_length=255)),
                ('metadata_wallet', models.JSONField(blank=True, null=True)),
                ('activo_inversion', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='asset.activoinversion')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
