# Generated by Django 3.2.18 on 2024-04-24 22:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0037_rename_contractaddress_activoinversionsmartcontract2_contract_address'),
        ('kaleido', '0008_alter_walletsmartcontract_type_wallet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='walletsmartcontract',
            name='activo_inversion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asset.activoinversion'),
        ),
    ]
