# Generated by Django 3.2.18 on 2023-09-08 15:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AccessTokenWeetrust',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.BooleanField(default=True)),
                ('value', models.TextField()),
            ],
            options={
                'ordering': ['-created_at'],
                'get_latest_by': 'created_at',
            },
        ),
        migrations.CreateModel(
            name='DocumentSesionResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.BooleanField(default=True)),
                ('expedition_country', models.CharField(max_length=128)),
                ('country_code', models.CharField(max_length=16)),
                ('document_type', models.CharField(max_length=128)),
                ('document_number', models.CharField(max_length=128)),
                ('document_front_image', models.TextField()),
                ('document_back_image', models.TextField(blank=True, null=True)),
                ('selfie', models.TextField()),
                ('response_data', models.JSONField(blank=True, null=True)),
                ('response_validation', models.JSONField(blank=True, null=True)),
                ('id_validation', models.BooleanField(default=False)),
                ('liveness', models.BooleanField(default=False)),
                ('face_recognition', models.BooleanField(default=False)),
                ('names_validation', models.BooleanField(default=False)),
                ('birth_date_validation', models.BooleanField(default=False)),
                ('doc_number_validation', models.BooleanField(default=False)),
                ('expedition_date_validation', models.BooleanField(default=False)),
                ('feedback_text', models.TextField(blank=True, default='', null=True)),
                ('user', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
